name: popan
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - numpy
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - pillow=5
  - opencv=3
  - jupyterlab
  - imagemagick
